diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel', 'rear_left_wheel']
  right_wheel: ['front_right_wheel', 'rear_right_wheel']
  publish_rate: 50
  pose_covariance_diagonal: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]  # TODO: set these
  twist_covariance_diagonal: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0] 
  cmd_vel_timeout: 0.25
