diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ["wheel_front_left", "wheel_back_left"]
  right_wheel: ["wheel_front_right", "wheel_back_right"]
  publish_rate: 50
  pose_covariance_diagonal: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  twist_covariance_diagonal: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0] 
  cmd_vel_timeout: 0.25
