name: rover
defaults:
  eds_pkg: rover_drive_controller
  eds_file: "config/C5_E.eds"
  motor_layer:
    switching_state: 4
  vel_to_device: "vel*60"
  vel_from_device: "obj6064/60"

nodes:
  wheel_front_left: 
    id: 1
    joint: front_left_wheel_joint
  wheel_front_right:
    id: 2
    joint: front_right_wheel_joint
